<img src="images/banner.png" style="width: 100%;">

# Web Scraping with Python

In [ ]:
# !conda install html5lib -y # You might need to instll html5lib for the proper HTML parsing

References:

[1] Mitchell, Ryan. *Web scraping with python.* " O'Reilly Media, Inc.", 2024.

[2] Chapagain, Anish. *Hands-On Web Scraping with Python: Extract quality data from the web using effective Python techniques.* Packt Publishing Ltd, 2023.

[3] Elridge, Taryn. *Web automation and scraping with Python: Hands-on mastery of selenium, beautifulsoup, and real-world data extraction.* 2025.

[4] Requests Documentation - https://requests.readthedocs.io/en/latest/user/quickstart/

[5] Beautiful Soup Documentation - https://beautiful-soup-4.readthedocs.io/en/latest/

[6] Revised and grammar checked using ChatGPT - https://chatgpt.com/

Prepared by: Leodegario Lorenzo II

This notebook introduces the fundamentals of web scraping using Python and the `BeautifulSoup` library.

In a nutshell, **web scraping** is the process of extracting data from websites programmatically. In other words, we’ll use Python to interact with web pages the way a human would through a browser—requesting pages, reading their content, and pulling out the information we care about.

In this demo, we’ll walk through:

1. How to make HTTP requests with Python
2. How to parse and navigate HTML documents with BeautifulSoup
3. Common design patterns and best practices for more advanced web scraping tasks

By the end, you should have a solid fundamentals for how web scraping works and the confidence to build your own scrapers responsibly.

## 0 Web Scraping Prerequisites

### `robots.txt`

Before scraping any website, you should first check the site’s `robots.txt` file. This file indicates which parts of the site the owner allows or disallows for automated access. Reviewing it helps you avoid scraping areas the site explicitly asks bots not to access, and sets a baseline for responsible, respectful scraping practices.

For most of the initial examples in this notebook, we'll be scraping the website from one of our primary reference - [pythonscraping.com](https://pythonscraping.com/). A quick look on its `robots.txt` file indicate that most of the pages are allowed for scraping, except for particular files and login-protected directories:

```
#
# robots.txt
#
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
#
# This file will be ignored unless it is at the root of your host:
# Used:    http://example.com/robots.txt
# Ignored: http://example.com/site/robots.txt
#
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/robotstxt.html
#
# For syntax checking, see:
# http://www.frobee.com/robots-txt-check

User-agent: *
Crawl-delay: 10
# Directories
Disallow: /includes/
Disallow: /misc/
Disallow: /modules/
Disallow: /profiles/
Disallow: /scripts/
Disallow: /themes/
# Files
Disallow: /CHANGELOG.txt
Disallow: /cron.php
Disallow: /INSTALL.mysql.txt
Disallow: /INSTALL.pgsql.txt
Disallow: /INSTALL.sqlite.txt
Disallow: /install.php
Disallow: /INSTALL.txt
Disallow: /LICENSE.txt
Disallow: /MAINTAINERS.txt
Disallow: /update.php
Disallow: /UPGRADE.txt
Disallow: /xmlrpc.php
# Paths (clean URLs)
Disallow: /admin/
Disallow: /comment/reply/
Disallow: /filter/tips/
Disallow: /node/add/
Disallow: /search/
Disallow: /user/register/
Disallow: /user/password/
Disallow: /user/login/
Disallow: /user/logout/
# Paths (no clean URLs)
Disallow: /?q=admin/
Disallow: /?q=comment/reply/
Disallow: /?q=filter/tips/
Disallow: /?q=node/add/
Disallow: /?q=search/
Disallow: /?q=user/password/
Disallow: /?q=user/register/
Disallow: /?q=user/login/
Disallow: /?q=user/logout/
```

We should also note that the recommended `crawl-delay` for this website is `10` seconds, and we should adhere to this as much as possible.

### Specifying the `User-Agent`

Aside from following the site’s `robots.txt` rules, it’s also good practice to identify your scraper when making requests by setting a clear `User-Agent` header. This lets website owners know who (or what) is accessing their site and helps your requests look like responsible traffic rather than anonymous or potentially malicious activity.

In [1]:
headers = {"User-Agent": "llorenzo-scraper/1.0(contact:llorenzo@aim.edu)"}

## 1 Performing HTTP requests using `requests`

`requests` is a simple HTTP library for Python which we will use to send client requests and interpret server responses programatically.

### General Usage

Let's look at some key features of the `requests` library.

In [2]:
from time import sleep

import requests

First, we demonstrate how we perform **GET** requests using `requests`.

In [3]:
url = 'http://pythonscraping.com/pages/page1.html'

response = requests.get(url, headers=headers)
sleep(10)

The above code generates a GET request from our client then the server response is collected into the variable `response`.

In [4]:
type(response)

requests.models.Response

The output is a `Response` object which has several useful attributes. First, we can check for the status code of the response:

In [5]:
response.status_code

200

There are several possible status codes, each of which describes the result of the requests. We list some of the important status codes below:

| Code | Description |
| :--- | :---------- |
| `200` | OK, request succeed |
| `404` | Not found, requested resource cannot be found |
| `403` | Access denied |
| `429` | Too many requests (rate-limited) |
| `500` | Internal server error |

If you encounter an HTTP status error, you’ll want to handle it gracefully so you can control how your program behaves when something goes wrong.

In practice, this usually means logging the error (for example, to a file) and deciding whether to retry, skip the request, or stop the program altogether. A common pattern you’ll see is using try–except blocks to catch and handle these errors cleanly.

In [7]:
url = 'http://pythonscraping.com/pages/page1337.html'
headers = {"User-Agent": "llorenzo-scraper/1.0(contact:llorenzo@aim.edu)"}

try:
    response = requests.get(url, headers=headers)
    sleep(10)
    response.raise_for_status()
except requests.RequestException as e:
    print("Failed to fetch page: ", e)

Failed to fetch page:  404 Client Error: Not Found for url: https://pythonscraping.com/pages/page1337.html

We will be using the above code multiple times throughout this notebook, thus, we might as well create a function for obtaining responses when we request for web pages.

In [8]:
def get_webpage(url, headers, sleep_time=10):
    """Perform GET request on a given url then collect the resulting
    response

    Parameters
    ----------
    url : str
        URL string of the website to be scraped
    headers : dict
        Set of key-value pairs to be passed as headers during the
        request
    sleep_time : numeric, default=10
        Delay time after the request

    Returns
    -------
    response : Response object
        Response of the server to the request
    """
    try:
        response = requests.get(url, headers=headers)
        sleep(sleep_time)
        response.raise_for_status()
    except requests.RequestException as e:
        print("Failed to fetch page: ", e)
    else:
        print(f"Page has been successfully fetched! {url}")

    return response

## 2 Web Scraping using `BeautifulSoup`

Now that we know how we can create requests from our client using Python, the next step is knowing how to parse the resulting HTML content and extract the data that we want from the website.

### Basic Usage of `BeautifulSoup`

Let's first get once again the `page1.html` from the `pythonscraping` website which contains a simple html file.

In [9]:
url = 'http://pythonscraping.com/pages/page1.html'
response = get_webpage(url, headers)

Page has been successfully fetched! http://pythonscraping.com/pages/page1.html

We can get the contents of the HTML file by calling the `content` attribute. Verify that the content is usually an HTML file. On usual requests you would get an HTML file, but there are websites also where the output can be of other format such as `xml` or `json` files.

In [10]:
response.content

b'<html>\n<head>\n<title>A Useful Page</title>\n</head>\n<body>\n<h1>An Interesting Title</h1>\n<div>\nLorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n</div>\n</body>\n</html>\n'

We can then use Beautiful Soup (`bs4`) to parse this HTML file. The most comonly used object in `bs4` is the `BeautifulSoup` object, which we import accordingly.

In [11]:
from bs4 import BeautifulSoup

When we use the `BeautifulSoup` object, we specify two parameters - the first is the HTML string object to parse, while the second specifies the parser that you want Beautiful Soup to use.

The currently supported parsers are `html.parser` (Python's built-in HTML parser), `lxml`, `html5lib`. Different parsers will create different parse trees from the same document. For more info please check the [documentation](https://beautiful-soup-4.readthedocs.io/en/latest/#differences-between-parsers).

If given a perfectly formed HTML, the data structure will be identical for different parsers. But if the HTML is not perfectly-formed, different parsers will give different results. Among the html parsers, the `html5lib` parser uses techniques that are part of the `HTML5` standard. Thus, this is what we'll be using on most of our examples.

In [12]:
soup = BeautifulSoup(response.content, 'html5lib')

Afterwards, the HTML will be parsed into an object with a hierarchical structure:

In [13]:
print(soup.prettify())

<html>
 <head>
  <title>
   A Useful Page
  </title>
 </head>
 <body>
  <h1>
   An Interesting Title
  </h1>
  <div>
   Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </div>
 </body>
</html>

The `BeautifulSoup` object represents the HTML document as a whole, meanwhile, a `Tag` object corresponds to an HTML tag in the original document.

In [14]:
soup.html

<html><head>
<title>A Useful Page</title>
</head>
<body>
<h1>An Interesting Title</h1>
<div>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</div>


</body></html>

In [15]:
soup.h1

You can traverse the document in one direction by chaining method calls of corresponding children tags.

In [16]:
soup.html.body

<body>
<h1>An Interesting Title</h1>
<div>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</div>


</body>

In [17]:
soup.html.body.h1

In [18]:
type(soup.html.body)

bs4.element.Tag

Each tag also has the `name` accessible as `.name`:

In [19]:
soup.html.body.name

'body'

In [20]:
soup.html.body.h1.name

'h1'

And you can extract the text within a tag using the `.text` attribute.

In [21]:
soup.html.body.h1.text

'An Interesting Title'

Or you can opt to use the `.get_text()` function for better readability.

In [23]:
soup.html.body.h1.get_text()

'An Interesting Title'

### Finding tags

To filter HTML pages and find only a list of desired elements, `BeautifulSoup` provides us with the `find()` and `find_all()` function.

- `find()` returns the first match. e.g. `soup.find('a')` returns the first HTML element with a `a` tag.
- `find_all()` returns a list of all matches. `soup.find_all('a')` returns an iterable of HTML elements with a `a` tag.

You can define filters as a string, regular expression, or a list, which matches the given input to the tag of the corresponding HTML element. The definition of the two functions is as follows:

```
find_all(tag, attrs, recursive, text, limit, **kwargs)
find(tag, attrs, recursive, text, **kwargs)
```

As an example of the usage of `find()` and `find_all()`, let's look at scraping the web page http://www.pythonscraping.com/pages/warandpeace.html

In [24]:
url = 'http://www.pythonscraping.com/pages/warandpeace.html'

response = get_webpage(url, headers)

Page has been successfully fetched! http://www.pythonscraping.com/pages/warandpeace.html

After successfully fetching the page, we proceed to create a `BeautifulSoup` object:

In [25]:
soup = BeautifulSoup(response.content, 'html5lib')

You'll notice that the spoken lines of the characters in the stories are highlighted in red, meanwhile the names of the characters are in green.

In [26]:
for line in soup.prettify().splitlines()[78: 85]:
    print(line)

     Heavens! what a virulent attack!
    </span>
    " replied
    <span class="green">
     the prince
    </span>
    , not in the

As such, we can extract all the character names by filtering all `span` elements with `class` having a value of `green`.

In [38]:
set([elem.text.replace('\n', ' ').lower() for elem in soup.find_all('span', {'class': ['green']})])

{'abbe morio',
 'anatole',
 'anna pavlovna',
 'anna pavlovna scherer',
 "anna pavlovna's",
 'baron funke',
 'dowager empress marya fedorovna',
 'empress marya fedorovna',
 'her majesty',
 'king of prussia',
 'le vicomte de mortemart',
 'montmorencys',
 'prince vasili',
 'prince vasili kuragin',
 'rohans',
 'st. petersburg',
 'the baron',
 'the emperor',
 'the empress',
 'the prince',
 'wintzingerode'}

### Navigating Trees

Recall that chaining tags enables you to navigate the `BeautifulSoup` tree in a single downward direction:

In [39]:
soup.body.div.p

<p>
It was in July, 1805, and the speaker was the well-known <span class="green">Anna
Pavlovna Scherer</span>, maid of honor and favorite of the <span class="green">Empress Marya
Fedorovna</span>. With these words she greeted <span class="green">Prince Vasili Kuragin</span>, a man
of high rank and importance, who was the first to arrive at her
reception. <span class="green">Anna Pavlovna</span> had had a cough for some days. She was, as
she said, suffering from la grippe; grippe being then a new word in
<span class="green">St. Petersburg</span>, used only by the elite.
</p>

If we want to get all the `<p>` tags within the first `<div>` tag in the document, or anything more complicated than the first tag within a certain level, we would need to use other methods to do so.

In the next subsection, we show how we can also traverse the tree further with more control using various attributes and functions. We'll demonstrate how to navigate the tree downards, upwards, and sideways.

#### Going down

If we want to get all the tags directly one below a certain tag, we can use the `.contents` or `.children` attribute.

In [42]:
soup.body.div.p.contents

['\nIt was in July, 1805, and the speaker was the well-known ',
 <span class="green">Anna
 Pavlovna Scherer</span>,
 ', maid of honor and favorite of the ',
 <span class="green">Empress Marya
 Fedorovna</span>,
 '. With these words she greeted ',
 <span class="green">Prince Vasili Kuragin</span>,
 ', a man\nof high rank and importance, who was the first to arrive at her\nreception. ',
 <span class="green">Anna Pavlovna</span>,
 ' had had a cough for some days. She was, as\nshe said, suffering from la grippe; grippe being then a new word in\n',
 <span class="green">St. Petersburg</span>,
 ', used only by the elite.\n']

In [44]:
list(soup.body.div.p.children)

['\nIt was in July, 1805, and the speaker was the well-known ',
 <span class="green">Anna
 Pavlovna Scherer</span>,
 ', maid of honor and favorite of the ',
 <span class="green">Empress Marya
 Fedorovna</span>,
 '. With these words she greeted ',
 <span class="green">Prince Vasili Kuragin</span>,
 ', a man\nof high rank and importance, who was the first to arrive at her\nreception. ',
 <span class="green">Anna Pavlovna</span>,
 ' had had a cough for some days. She was, as\nshe said, suffering from la grippe; grippe being then a new word in\n',
 <span class="green">St. Petersburg</span>,
 ', used only by the elite.\n']

If you want to go deeper than one level, you can use the `.descendants` function instead.

In [45]:
list(soup.body.div.p.descendants)

['\nIt was in July, 1805, and the speaker was the well-known ',
 <span class="green">Anna
 Pavlovna Scherer</span>,
 'Anna\nPavlovna Scherer',
 ', maid of honor and favorite of the ',
 <span class="green">Empress Marya
 Fedorovna</span>,
 'Empress Marya\nFedorovna',
 '. With these words she greeted ',
 <span class="green">Prince Vasili Kuragin</span>,
 'Prince Vasili Kuragin',
 ', a man\nof high rank and importance, who was the first to arrive at her\nreception. ',
 <span class="green">Anna Pavlovna</span>,
 'Anna Pavlovna',
 ' had had a cough for some days. She was, as\nshe said, suffering from la grippe; grippe being then a new word in\n',
 <span class="green">St. Petersburg</span>,
 'St. Petersburg',
 ', used only by the elite.\n']

In [46]:
len(list(soup.body.div.p.descendants))

16

In [47]:
len(list(soup.body.div.p.children))

11

If we only want to get only the strings or text within the text of the descendants of a tag, we can use the `.strings` method.

In [50]:
list(soup.body.div.p.strings)

['\nIt was in July, 1805, and the speaker was the well-known ',
 'Anna\nPavlovna Scherer',
 ', maid of honor and favorite of the ',
 'Empress Marya\nFedorovna',
 '. With these words she greeted ',
 'Prince Vasili Kuragin',
 ', a man\nof high rank and importance, who was the first to arrive at her\nreception. ',
 'Anna Pavlovna',
 ' had had a cough for some days. She was, as\nshe said, suffering from la grippe; grippe being then a new word in\n',
 'St. Petersburg',
 ', used only by the elite.\n']

In [51]:
type(list(soup.body.div.p.strings)[0])

bs4.element.NavigableString

In [54]:
list(list(soup.body.div.p.strings)[0].parents)

[<p>
 It was in July, 1805, and the speaker was the well-known <span class="green">Anna
 Pavlovna Scherer</span>, maid of honor and favorite of the <span class="green">Empress Marya
 Fedorovna</span>. With these words she greeted <span class="green">Prince Vasili Kuragin</span>, a man
 of high rank and importance, who was the first to arrive at her
 reception. <span class="green">Anna Pavlovna</span> had had a cough for some days. She was, as
 she said, suffering from la grippe; grippe being then a new word in
 <span class="green">St. Petersburg</span>, used only by the elite.
 </p>,
 <div id="text">
 "<span class="red">Well, Prince, so Genoa and Lucca are now just family estates of the
 Buonapartes. But I warn you, if you don't tell me that this means war,
 if you still try to defend the infamies and horrors perpetrated by
 that Antichrist- I really believe he is Antichrist- I will have
 nothing more to do with you and you are no longer my friend, no longer
 my 'faithful slave,' as you call yourself! But how do you do? I see
 I have frightened you- sit down and tell me all the news.</span>"
 <p>
 It was in July, 1805, and the speaker was the well-known <span class="green">Anna
 Pavlovna Scherer</span>, maid of honor and favorite of the <span class="green">Empress Marya
 Fedorovna</span>. With these words she greeted <span class="green">Prince Vasili Kuragin</span>, a man
 of high rank and importance, who was the first to arrive at her
 reception. <span class="green">Anna Pavlovna</span> had had a cough for some days. She was, as
 she said, suffering from la grippe; grippe being then a new word in
 <span class="green">St. Petersburg</span>, used only by the elite.
 </p><p>
 All her invitations without exception, written in French, and
 delivered by a scarlet-liveried footman that morning, ran as follows:
 </p><p>
 "<span class="red">If you have nothing better to do, Count [or Prince], and if the
 prospect of spending an evening with a poor invalid is not too
 terrible, I shall be very charmed to see you tonight between 7 and 10-
 Annette Scherer.</span>"
 </p><p>
 "<span class="red">Heavens! what a virulent attack!</span>" replied <span class="green">the prince</span>, not in the
 least disconcerted by this reception. He had just entered, wearing
 an embroidered court uniform, knee breeches, and shoes, and had
 stars on his breast and a serene expression on his flat face. He spoke
 in that refined French in which our grandfathers not only spoke but
 thought, and with the gentle, patronizing intonation natural to a
 man of importance who had grown old in society and at court. He went
 up to <span class="green">Anna Pavlovna</span>, kissed her hand, presenting to her his bald,
 scented, and shining head, and complacently seated himself on the
 sofa.
 </p><p>
 "<span class="red">First of all, dear friend, tell me how you are. Set your friend's
 mind at rest,</span>" said he without altering his tone, beneath the
 politeness and affected sympathy of which indifference and even
 irony could be discerned.
 </p><p>
 "<span class="red">Can one be well while suffering morally? Can one be calm in times
 like these if one has any feeling?</span>" said <span class="green">Anna Pavlovna</span>. "<span class="red">You are
 staying the whole evening, I hope?</span>"
 </p><p>
 "<span class="red">And the fete at the English ambassador's? Today is Wednesday. I
 must put in an appearance there,</span>" said <span class="green">the prince</span>. "<span class="red">My daughter is
 coming for me to take me there.</span>"
 </p><p>
 "<span class="red">I thought today's fete had been canceled. I confess all these
 festivities and fireworks are becoming wearisome.</span>"
 </p><p>
 "<span class="red">If they had known that you wished it, the entertainment would
 have been put off,</span>" said <span class="green">the prince</span>, who, like a wound-up clock, by
 force of habit said things he did not even wish to be believed.
 </p><p>
 "<span class="red">Don't tease! Well, and what has been decided about Novosiltsev's
 dispatch? You know everything.</span>"
 </p><p>
 "<span class="red">What can one say about it?</span>" replied <span class="green">the prince</span> in a cold,
 listless tone. "<span class="red">What has been decided? They have decided that
 Buonaparte has burnt his boats, and I believe that we are ready to
 burn ours.</span>"
 </p><p>
 <span class="green">Prince Vasili</span> always spoke languidly, like an actor repeating a
 stale part. <span class="green">Anna Pavlovna</span> Scherer on the contrary, despite her forty
 years, overflowed with animation and impulsiveness. To be an
 enthusiast had become her social vocation and, sometimes even when she
 did not feel like it, she became enthusiastic in order not to
 disappoint the expectations of those who knew her. The subdued smile
 which, though it did not suit her faded features, always played
 round her lips expressed, as in a spoiled child, a continual
 consciousness of her charming defect, which she neither wished, nor
 could, nor considered it necessary, to correct.
 </p><p>
 In the midst of a conversation on political matters <span class="green">Anna Pavlovna</span>
 burst out:
 </p><p>
 "<span class="red">Oh, don't speak to me of Austria. Perhaps I don't understand
 things, but Austria never has wished, and does not wish, for war.
 She is betraying us! Russia alone must save Europe. Our gracious
 sovereign recognizes his high vocation and will be true to it. That is
 the one thing I have faith in! Our good and wonderful sovereign has to
 perform the noblest role on earth, and he is so virtuous and noble
 that God will not forsake him. He will fulfill his vocation and
 crush the hydra of revolution, which has become more terrible than
 ever in the person of this murderer and villain! We alone must
 avenge the blood of the just one.... Whom, I ask you, can we rely
 on?... England with her commercial spirit will not and cannot
 understand the Emperor Alexander's loftiness of soul. She has
 refused to evacuate Malta. She wanted to find, and still seeks, some
 secret motive in our actions. What answer did Novosiltsev get? None.
 The English have not understood and cannot understand the
 self-abnegation of our Emperor who wants nothing for himself, but only
 desires the good of mankind. And what have they promised? Nothing! And
 what little they have promised they will not perform! Prussia has
 always declared that Buonaparte is invincible, and that all Europe
 is powerless before him.... And I don't believe a word that Hardenburg
 says, or Haugwitz either. This famous Prussian neutrality is just a
 trap. I have faith only in God and the lofty destiny of our adored
 monarch. He will save Europe!</span>"
 </p><p>
 She suddenly paused, smiling at her own impetuosity.
 </p><p>
 "<span class="red">I think,</span>" said <span class="green">the prince</span> with a smile, "<span class="red">that if you had been
 sent instead of our dear <span class="green">Wintzingerode</span> you would have captured the
 <span class="green">King of Prussia</span>'s consent by assault. You are so eloquent. Will you
 give me a cup of tea?</span>"
 </p><p>
 "<span class="red">In a moment. A propos,</span>" she added, becoming calm again, "<span class="red">I am
 expecting two very interesting men tonight, <span class="green">le Vicomte de Mortemart</span>,
 who is connected with the <span class="green">Montmorencys</span> through the <span class="green">Rohans</span>, one of
 the best French families. He is one of the genuine emigres, the good
 ones. And also the <span class="green">Abbe Morio</span>. Do you know that profound thinker? He
 has been received by <span class="green">the Emperor</span>. Had you heard?</span>"
 </p><p>
 "<span class="red">I shall be delighted to meet them,</span>" said <span class="green">the prince</span>. "<span class="red">But tell me,</span>"
 he added with studied carelessness as if it had only just occurred
 to him, though the question he was about to ask was the chief motive
 of his visit, "<span class="red">is it true that the Dowager Empress wants Baron Funke
 to be appointed first secretary at Vienna? The baron by all accounts
 is a poor creature.</span>"
 </p><p>
 <span class="green">Prince Vasili</span> wished to obtain this post for his son, but others
 were trying through the <span class="green">Dowager Empress Marya Fedorovna</span> to secure it
 for <span class="green">the baron</span>.
 </p><p>
 <span class="green">Anna Pavlovna</span> almost closed her eyes to indicate that neither she
 nor anyone else had a right to criticize what <span class="green">the Empress</span> desired or
 was pleased with.
 </p><p>
 "<span class="red">Baron Funke has been recommended to the Dowager Empress by her
 sister,</span>" was all she said, in a dry and mournful tone.
 </p><p>
 As she named <span class="green">the Empress</span>, <span class="green">Anna Pavlovna's</span> face suddenly assumed an
 expression of profound and sincere devotion and respect mingled with
 sadness, and this occurred every time she mentioned her illustrious
 patroness. She added that <span class="green">Her Majesty</span> had deigned to show <span class="green">Baron
 Funke</span>, and again her face clouded over with sadness.
 </p><p>
 <span class="green">The prince</span> was silent and looked indifferent. But, with the
 womanly and courtierlike quickness and tact habitual to her, <span class="green">Anna
 Pavlovna</span> wished both to rebuke him (for daring to speak he had done of
 a man recommended to <span class="green">the Empress</span>) and at the same time to console him,
 so she said:
 </p><p>
 "<span class="red">Now about your family. Do you know that since your daughter came
 out everyone has been enraptured by her? They say she is amazingly
 beautiful.</span>"
 </p><p>
 <span class="green">The prince</span> bowed to signify his respect and gratitude.
 </p><p>
 "<span class="red">I often think,</span>" she continued after a short pause, drawing nearer
 to the prince and smiling amiably at him as if to show that
 political and social topics were ended and the time had come for
 intimate conversation- "<span class="red">I often think how unfairly sometimes the
 joys of life are distributed. Why has fate given you two such splendid
 children? I don't speak of <span class="green">Anatole</span>, your youngest. I don't like
 him,</span>" she added in a tone admitting of no rejoinder and raising her
 eyebrows. "<span class="red">Two such charming children. And really you appreciate
 them less than anyone, and so you don't deserve to have them.</span>"
 </p><p>
 And she smiled her ecstatic smile.
 </p><p>
 "<span class="red">I can't help it,</span>" said <span class="green">the prince</span>. "<span class="red">Lavater would have said I
 lack the bump of paternity.</span>"
 </p><p>
 "<span class="red">Don't joke; I mean to have a serious talk with you. Do you know I
 am dissatisfied with your younger son? Between ourselves</span>" (and her
 face assumed its melancholy expression), "<span class="red">he was mentioned at Her
 Majesty's and you were pitied....</span>"
 </p><p>
 <span class="green">The prince</span> answered nothing, but she looked at him significantly,
 awaiting a reply. He frowned.
 </p><p>
 "<span class="red">What would you have me do?</span>" he said at last. "<span class="red">You know I did all
 a father could for their education, and they have both turned out
 fools. Hippolyte is at least a quiet fool, but Anatole is an active
 one. That is the only difference between them.</span>" He said this smiling
 in a way more natural and animated than usual, so that the wrinkles
 round his mouth very clearly revealed something unexpectedly coarse
 and unpleasant.
 </p><p>
 "<span class="red">And why are children born to such men as you? If you were not a
 father there would be nothing I could reproach you with,</span>" said <span class="green">Anna
 Pavlovna</span>, looking up pensively.
 </p><p>
 "<span class="red">I am your faithful slave and to you alone I can confess that my
 children are the bane of my life. It is the cross I have to bear. That
 is how I explain it to myself. It can't be helped!</span>"
 </p><p>
 He said no more, but expressed his resignation to cruel fate by a
 gesture. <span class="green">Anna Pavlovna</span> meditated.
 </p></div>,
 <body>
 <h1>War and Peace</h1>
 <h2>Chapter 1</h2>
 <div id="text">
 "<span class="red">Well, Prince, so Genoa and Lucca are now just family estates of the
 Buonapartes. But I warn you, if you don't tell me that this means war,
 if you still try to defend the infamies and horrors perpetrated by
 that Antichrist- I really believe he is Antichrist- I will have
 nothing more to do with you and you are no longer my friend, no longer
 my 'faithful slave,' as you call yourself! But how do you do? I see
 I have frightened you- sit down and tell me all the news.</span>"
 <p>
 It was in July, 1805, and the speaker was the well-known <span class="green">Anna
 Pavlovna Scherer</span>, maid of honor and favorite of the <span class="green">Empress Marya
 Fedorovna</span>. With these words she greeted <span class="green">Prince Vasili Kuragin</span>, a man
 of high rank and importance, who was the first to arrive at her
 reception. <span class="green">Anna Pavlovna</span> had had a cough for some days. She was, as
 she said, suffering from la grippe; grippe being then a new word in
 <span class="green">St. Petersburg</span>, used only by the elite.
 </p><p>
 All her invitations without exception, written in French, and
 delivered by a scarlet-liveried footman that morning, ran as follows:
 </p><p>
 "<span class="red">If you have nothing better to do, Count [or Prince], and if the
 prospect of spending an evening with a poor invalid is not too
 terrible, I shall be very charmed to see you tonight between 7 and 10-
 Annette Scherer.</span>"
 </p><p>
 "<span class="red">Heavens! what a virulent attack!</span>" replied <span class="green">the prince</span>, not in the
 least disconcerted by this reception. He had just entered, wearing
 an embroidered court uniform, knee breeches, and shoes, and had
 stars on his breast and a serene expression on his flat face. He spoke
 in that refined French in which our grandfathers not only spoke but
 thought, and with the gentle, patronizing intonation natural to a
 man of importance who had grown old in society and at court. He went
 up to <span class="green">Anna Pavlovna</span>, kissed her hand, presenting to her his bald,
 scented, and shining head, and complacently seated himself on the
 sofa.
 </p><p>
 "<span class="red">First of all, dear friend, tell me how you are. Set your friend's
 mind at rest,</span>" said he without altering his tone, beneath the
 politeness and affected sympathy of which indifference and even
 irony could be discerned.
 </p><p>
 "<span class="red">Can one be well while suffering morally? Can one be calm in times
 like these if one has any feeling?</span>" said <span class="green">Anna Pavlovna</span>. "<span class="red">You are
 staying the whole evening, I hope?</span>"
 </p><p>
 "<span class="red">And the fete at the English ambassador's? Today is Wednesday. I
 must put in an appearance there,</span>" said <span class="green">the prince</span>. "<span class="red">My daughter is
 coming for me to take me there.</span>"
 </p><p>
 "<span class="red">I thought today's fete had been canceled. I confess all these
 festivities and fireworks are becoming wearisome.</span>"
 </p><p>
 "<span class="red">If they had known that you wished it, the entertainment would
 have been put off,</span>" said <span class="green">the prince</span>, who, like a wound-up clock, by
 force of habit said things he did not even wish to be believed.
 </p><p>
 "<span class="red">Don't tease! Well, and what has been decided about Novosiltsev's
 dispatch? You know everything.</span>"
 </p><p>
 "<span class="red">What can one say about it?</span>" replied <span class="green">the prince</span> in a cold,
 listless tone. "<span class="red">What has been decided? They have decided that
 Buonaparte has burnt his boats, and I believe that we are ready to
 burn ours.</span>"
 </p><p>
 <span class="green">Prince Vasili</span> always spoke languidly, like an actor repeating a
 stale part. <span class="green">Anna Pavlovna</span> Scherer on the contrary, despite her forty
 years, overflowed with animation and impulsiveness. To be an
 enthusiast had become her social vocation and, sometimes even when she
 did not feel like it, she became enthusiastic in order not to
 disappoint the expectations of those who knew her. The subdued smile
 which, though it did not suit her faded features, always played
 round her lips expressed, as in a spoiled child, a continual
 consciousness of her charming defect, which she neither wished, nor
 could, nor considered it necessary, to correct.
 </p><p>
 In the midst of a conversation on political matters <span class="green">Anna Pavlovna</span>
 burst out:
 </p><p>
 "<span class="red">Oh, don't speak to me of Austria. Perhaps I don't understand
 things, but Austria never has wished, and does not wish, for war.
 She is betraying us! Russia alone must save Europe. Our gracious
 sovereign recognizes his high vocation and will be true to it. That is
 the one thing I have faith in! Our good and wonderful sovereign has to
 perform the noblest role on earth, and he is so virtuous and noble
 that God will not forsake him. He will fulfill his vocation and
 crush the hydra of revolution, which has become more terrible than
 ever in the person of this murderer and villain! We alone must
 avenge the blood of the just one.... Whom, I ask you, can we rely
 on?... England with her commercial spirit will not and cannot
 understand the Emperor Alexander's loftiness of soul. She has
 refused to evacuate Malta. She wanted to find, and still seeks, some
 secret motive in our actions. What answer did Novosiltsev get? None.
 The English have not understood and cannot understand the
 self-abnegation of our Emperor who wants nothing for himself, but only
 desires the good of mankind. And what have they promised? Nothing! And
 what little they have promised they will not perform! Prussia has
 always declared that Buonaparte is invincible, and that all Europe
 is powerless before him.... And I don't believe a word that Hardenburg
 says, or Haugwitz either. This famous Prussian neutrality is just a
 trap. I have faith only in God and the lofty destiny of our adored
 monarch. He will save Europe!</span>"
 </p><p>
 She suddenly paused, smiling at her own impetuosity.
 </p><p>
 "<span class="red">I think,</span>" said <span class="green">the prince</span> with a smile, "<span class="red">that if you had been
 sent instead of our dear <span class="green">Wintzingerode</span> you would have captured the
 <span class="green">King of Prussia</span>'s consent by assault. You are so eloquent. Will you
 give me a cup of tea?</span>"
 </p><p>
 "<span class="red">In a moment. A propos,</span>" she added, becoming calm again, "<span class="red">I am
 expecting two very interesting men tonight, <span class="green">le Vicomte de Mortemart</span>,
 who is connected with the <span class="green">Montmorencys</span> through the <span class="green">Rohans</span>, one of
 the best French families. He is one of the genuine emigres, the good
 ones. And also the <span class="green">Abbe Morio</span>. Do you know that profound thinker? He
 has been received by <span class="green">the Emperor</span>. Had you heard?</span>"
 </p><p>
 "<span class="red">I shall be delighted to meet them,</span>" said <span class="green">the prince</span>. "<span class="red">But tell me,</span>"
 he added with studied carelessness as if it had only just occurred
 to him, though the question he was about to ask was the chief motive

Or `.stripped_strings` if we want to delete the trailing and leading whitespaces in each strings.

In [55]:
list(soup.body.div.p.stripped_strings)

['It was in July, 1805, and the speaker was the well-known',
 'Anna\nPavlovna Scherer',
 ', maid of honor and favorite of the',
 'Empress Marya\nFedorovna',
 '. With these words she greeted',
 'Prince Vasili Kuragin',
 ', a man\nof high rank and importance, who was the first to arrive at her\nreception.',
 'Anna Pavlovna',
 'had had a cough for some days. She was, as\nshe said, suffering from la grippe; grippe being then a new word in',
 'St. Petersburg',
 ', used only by the elite.']

#### Going Up

You can also access an element's parent with the `.parent` attribute.

In [56]:
soup.body.div.p.span.parent

<p>
It was in July, 1805, and the speaker was the well-known <span class="green">Anna
Pavlovna Scherer</span>, maid of honor and favorite of the <span class="green">Empress Marya
Fedorovna</span>. With these words she greeted <span class="green">Prince Vasili Kuragin</span>, a man
of high rank and importance, who was the first to arrive at her
reception. <span class="green">Anna Pavlovna</span> had had a cough for some days. She was, as
she said, suffering from la grippe; grippe being then a new word in
<span class="green">St. Petersburg</span>, used only by the elite.
</p>

#### Going Sideways

We can also use the `.next_sibling` and `.previous_sibling` to navigate between page elements that are on the same level of the parse tree:

In [58]:
soup.div.p.next_sibling

<p>
All her invitations without exception, written in French, and
delivered by a scarlet-liveried footman that morning, ran as follows:
</p>

In [59]:
soup.div.p.previous_sibling

'"\n'

In [60]:
soup.div.p.next_sibling.previous_sibling

<p>
It was in July, 1805, and the speaker was the well-known <span class="green">Anna
Pavlovna Scherer</span>, maid of honor and favorite of the <span class="green">Empress Marya
Fedorovna</span>. With these words she greeted <span class="green">Prince Vasili Kuragin</span>, a man
of high rank and importance, who was the first to arrive at her
reception. <span class="green">Anna Pavlovna</span> had had a cough for some days. She was, as
she said, suffering from la grippe; grippe being then a new word in
<span class="green">St. Petersburg</span>, used only by the elite.
</p>

Or if we want to list all the tags within the same level of the current tag, we can use `.next_siblings` or `.previous_siblings`

In [63]:
list(soup.div.p.next_siblings)[:2]

[<p>
 All her invitations without exception, written in French, and
 delivered by a scarlet-liveried footman that morning, ran as follows:
 </p>,
 <p>
 "<span class="red">If you have nothing better to do, Count [or Prince], and if the
 prospect of spending an evening with a poor invalid is not too
 terrible, I shall be very charmed to see you tonight between 7 and 10-
 Annette Scherer.</span>"
 </p>]

<div class="alert alert-info" role="info">

  <b>Example 1: A Totally Normal Gifts Website</b>

  Retrieve and extract the item titles, description, cost, and image url of the gifts found from the website https://www.pythonscraping.com/pages/page3.html. Place the result in a `pandas` `DataFrame`.

</div>

In [64]:
url = 'https://www.pythonscraping.com/pages/page3.html'

response = get_webpage(url, headers)

Page has been successfully fetched! https://www.pythonscraping.com/pages/page3.html

In [65]:
soup = BeautifulSoup(response.content, 'html5lib')

In [66]:
print(soup.prettify())

<html>
 <head>
  <style>
   img{
	width:75px;
}
table{
	width:50%;
}
td{
	margin:10px;
	padding:10px;
}
.wrapper{
	width:800px;
}
.excitingNote{
	font-style:italic;
	font-weight:bold;
}
  </style>
 </head>
 <body>
  <div id="wrapper">
   <img src="../img/gifts/logo.jpg" style="float:left;"/>
   <h1>
    Totally Normal Gifts
   </h1>
   <div id="content">
    Here is a collection of totally normal, totally reasonable gifts that your friends are sure to love! Our collection is
hand-curated by well-paid, free-range Tibetan monks.
    <p>
     We haven't figured out how to make online shopping carts yet, but you can send us a check to:
     <br/>
     123 Main St.
     <br/>
     Abuja, Nigeria
     <br/>
     We will then send your totally amazing gift, pronto! Please include an extra $5.00 for gift wrapping.
    </p>
   </div>
   <table id="giftList">
    <tbody>
     <tr>
      <th>
       Item Title
      </th>
      <th>
       Description
      </th>
      <th>
       Cost
      </th>
      <th>
       Image
      </th>
     </tr>
     <tr class="gift" id="gift1">
      <td>
       Vegetable Basket
      </td>
      <td>
       This vegetable basket is the perfect gift for your health conscious (or overweight) friends!
       <span class="excitingNote">
        Now with super-colorful bell peppers!
       </span>
      </td>
      <td>
       $15.00
      </td>
      <td>
       <img src="../img/gifts/img1.jpg"/>
      </td>
     </tr>
     <tr class="gift" id="gift2">
      <td>
       Russian Nesting Dolls
      </td>
      <td>
       Hand-painted by trained monkeys, these exquisite dolls are priceless! And by "priceless," we mean "extremely expensive"!
       <span class="excitingNote">
        8 entire dolls per set! Octuple the presents!
       </span>
      </td>
      <td>
       $10,000.52
      </td>
      <td>
       <img src="../img/gifts/img2.jpg"/>
      </td>
     </tr>
     <tr class="gift" id="gift3">
      <td>
       Fish Painting
      </td>
      <td>
       If something seems fishy about this painting, it's because it's a fish!
       <span class="excitingNote">
        Also hand-painted by trained monkeys!
       </span>
      </td>
      <td>
       $10,005.00
      </td>
      <td>
       <img src="../img/gifts/img3.jpg"/>
      </td>
     </tr>
     <tr class="gift" id="gift4">
      <td>
       Dead Parrot
      </td>
      <td>
       This is an ex-parrot!
       <span class="excitingNote">
        Or maybe he's only resting?
       </span>
      </td>
      <td>
       $0.50
      </td>
      <td>
       <img src="../img/gifts/img4.jpg"/>
      </td>
     </tr>
     <tr class="gift" id="gift5">
      <td>
       Mystery Box
      </td>
      <td>
       If you love suprises, this mystery box is for you! Do not place on light-colored surfaces. May cause oil staining.
       <span class="excitingNote">
        Keep your friends guessing!
       </span>
      </td>
      <td>
       $1.50
      </td>
      <td>
       <img src="../img/gifts/img6.jpg"/>
      </td>
     </tr>
    </tbody>
   </table>
   <p>
   </p>
   <div id="footer">
    © Totally Normal Gifts, Inc.
    <br/>
    +234 (617) 863-0736
   </div>
  </div>
 </body>
</html>

In [67]:
import pandas as pd

In [71]:
list(soup.tr.next_siblings)

['\n\n',
 <tr class="gift" id="gift1"><td>
 Vegetable Basket
 </td><td>
 This vegetable basket is the perfect gift for your health conscious (or overweight) friends!
 <span class="excitingNote">Now with super-colorful bell peppers!</span>
 </td><td>
 $15.00
 </td><td>
 <img src="../img/gifts/img1.jpg"/>
 </td></tr>,
 '\n\n',
 <tr class="gift" id="gift2"><td>
 Russian Nesting Dolls
 </td><td>
 Hand-painted by trained monkeys, these exquisite dolls are priceless! And by "priceless," we mean "extremely expensive"! <span class="excitingNote">8 entire dolls per set! Octuple the presents!</span>
 </td><td>
 $10,000.52
 </td><td>
 <img src="../img/gifts/img2.jpg"/>
 </td></tr>,
 '\n\n',
 <tr class="gift" id="gift3"><td>
 Fish Painting
 </td><td>
 If something seems fishy about this painting, it's because it's a fish! <span class="excitingNote">Also hand-painted by trained monkeys!</span>
 </td><td>
 $10,005.00
 </td><td>
 <img src="../img/gifts/img3.jpg"/>
 </td></tr>,
 '\n\n',
 <tr class="gift" id="gift4"><td>
 Dead Parrot
 </td><td>
 This is an ex-parrot! <span class="excitingNote">Or maybe he's only resting?</span>
 </td><td>
 $0.50
 </td><td>
 <img src="../img/gifts/img4.jpg"/>
 </td></tr>,
 '\n\n',
 <tr class="gift" id="gift5"><td>
 Mystery Box
 </td><td>
 If you love suprises, this mystery box is for you! Do not place on light-colored surfaces. May cause oil staining. <span class="excitingNote">Keep your friends guessing!</span>
 </td><td>
 $1.50
 </td><td>
 <img src="../img/gifts/img6.jpg"/>
 </td></tr>,
 '\n']

In [72]:
soup.tr.find_all('tr')

[]

In [69]:
soup.tr.find_next_siblings('tr')

[<tr class="gift" id="gift1"><td>
 Vegetable Basket
 </td><td>
 This vegetable basket is the perfect gift for your health conscious (or overweight) friends!
 <span class="excitingNote">Now with super-colorful bell peppers!</span>
 </td><td>
 $15.00
 </td><td>
 <img src="../img/gifts/img1.jpg"/>
 </td></tr>,
 <tr class="gift" id="gift2"><td>
 Russian Nesting Dolls
 </td><td>
 Hand-painted by trained monkeys, these exquisite dolls are priceless! And by "priceless," we mean "extremely expensive"! <span class="excitingNote">8 entire dolls per set! Octuple the presents!</span>
 </td><td>
 $10,000.52
 </td><td>
 <img src="../img/gifts/img2.jpg"/>
 </td></tr>,
 <tr class="gift" id="gift3"><td>
 Fish Painting
 </td><td>
 If something seems fishy about this painting, it's because it's a fish! <span class="excitingNote">Also hand-painted by trained monkeys!</span>
 </td><td>
 $10,005.00
 </td><td>
 <img src="../img/gifts/img3.jpg"/>
 </td></tr>,
 <tr class="gift" id="gift4"><td>
 Dead Parrot
 </td><td>
 This is an ex-parrot! <span class="excitingNote">Or maybe he's only resting?</span>
 </td><td>
 $0.50
 </td><td>
 <img src="../img/gifts/img4.jpg"/>
 </td></tr>,
 <tr class="gift" id="gift5"><td>
 Mystery Box
 </td><td>
 If you love suprises, this mystery box is for you! Do not place on light-colored surfaces. May cause oil staining. <span class="excitingNote">Keep your friends guessing!</span>
 </td><td>
 $1.50
 </td><td>
 <img src="../img/gifts/img6.jpg"/>
 </td></tr>]

In [79]:
row = [elem.text.strip() for elem in soup.tr.find_next_siblings('tr')[0].children]
row

['Vegetable Basket',
 'This vegetable basket is the perfect gift for your health conscious (or overweight) friends!\nNow with super-colorful bell peppers!',
 '$15.00',
 '']

In [84]:
row[-1] = list(soup.tr.find_next_siblings('tr')[0].children)[-1].img['src']

In [85]:
row

['Vegetable Basket',
 'This vegetable basket is the perfect gift for your health conscious (or overweight) friends!\nNow with super-colorful bell peppers!',
 '$15.00',
 '../img/gifts/img1.jpg']

In [88]:
gifts = []
for element in soup.tr.find_next_siblings('tr'):
    row = [elem.text.strip() for elem in element.children]
    row[-1] = list(element.children)[-1].img['src']
    gifts.append(row)
pd.DataFrame(gifts, columns=['item', 'description', 'cost', 'image_url'])

,item,description,cost,image_url
0,Vegetable Basket,This vegetable basket is the perfect gift for ...,$15.00,../img/gifts/img1.jpg
1,Russian Nesting Dolls,"Hand-painted by trained monkeys, these exquisi...","$10,000.52",../img/gifts/img2.jpg
2,Fish Painting,"If something seems fishy about this painting, ...","$10,005.00",../img/gifts/img3.jpg
3,Dead Parrot,This is an ex-parrot! Or maybe he's only resting?,$0.50,../img/gifts/img4.jpg
4,Mystery Box,"If you love suprises, this mystery box is for ...",$1.50,../img/gifts/img6.jpg

## 3 Advanced Data Extraction with `BeautifulSoup`

We have demonstrated the basic features of `BeautifulSoup` which involves finding and accessing tags and attributes. We build on these tools further by introducing CSS selectors for precise targetting then also showing how we can also extract multiple pages or even multiple sites.

### CSS Selectors

CSS selectors can select elements baed on tags, classes, IDs, or attributes. The basic CSS selector syntax is as follows:

- `tag`: Selects all `<tag>` elements
- `.class`: Selects elements with `class="class"`
- `#id`: Selects an element with `id="id"`
- `[attribute="value"]`: Selects an element with the specified attribute.

You can use CSS selectors using `BeautifulSoup` through the `select()` method.

As an example, we select specific elements on the previously scraped website.

In [89]:
soup.select('tr#gift2')

[<tr class="gift" id="gift2"><td>
 Russian Nesting Dolls
 </td><td>
 Hand-painted by trained monkeys, these exquisite dolls are priceless! And by "priceless," we mean "extremely expensive"! <span class="excitingNote">8 entire dolls per set! Octuple the presents!</span>
 </td><td>
 $10,000.52
 </td><td>
 <img src="../img/gifts/img2.jpg"/>
 </td></tr>]

<div class="alert alert-info" role="info">

  <b>Example 2: A Totally Normal Gifts Website</b>

  Retrieve and extract the item titles, description, cost, and image url of the gifts found from the website https://www.pythonscraping.com/pages/page3.html using **CSS selectors**. Place the result in a `pandas` `DataFrame`.

</div>

In [90]:
soup.select('tr.gift')

[<tr class="gift" id="gift1"><td>
 Vegetable Basket
 </td><td>
 This vegetable basket is the perfect gift for your health conscious (or overweight) friends!
 <span class="excitingNote">Now with super-colorful bell peppers!</span>
 </td><td>
 $15.00
 </td><td>
 <img src="../img/gifts/img1.jpg"/>
 </td></tr>,
 <tr class="gift" id="gift2"><td>
 Russian Nesting Dolls
 </td><td>
 Hand-painted by trained monkeys, these exquisite dolls are priceless! And by "priceless," we mean "extremely expensive"! <span class="excitingNote">8 entire dolls per set! Octuple the presents!</span>
 </td><td>
 $10,000.52
 </td><td>
 <img src="../img/gifts/img2.jpg"/>
 </td></tr>,
 <tr class="gift" id="gift3"><td>
 Fish Painting
 </td><td>
 If something seems fishy about this painting, it's because it's a fish! <span class="excitingNote">Also hand-painted by trained monkeys!</span>
 </td><td>
 $10,005.00
 </td><td>
 <img src="../img/gifts/img3.jpg"/>
 </td></tr>,
 <tr class="gift" id="gift4"><td>
 Dead Parrot
 </td><td>
 This is an ex-parrot! <span class="excitingNote">Or maybe he's only resting?</span>
 </td><td>
 $0.50
 </td><td>
 <img src="../img/gifts/img4.jpg"/>
 </td></tr>,
 <tr class="gift" id="gift5"><td>
 Mystery Box
 </td><td>
 If you love suprises, this mystery box is for you! Do not place on light-colored surfaces. May cause oil staining. <span class="excitingNote">Keep your friends guessing!</span>
 </td><td>
 $1.50
 </td><td>
 <img src="../img/gifts/img6.jpg"/>
 </td></tr>]

In [95]:
row = [elem.text.strip() for elem in soup.select('tr.gift')[0].select('td')]
row

['Vegetable Basket',
 'This vegetable basket is the perfect gift for your health conscious (or overweight) friends!\nNow with super-colorful bell peppers!',
 '$15.00',
 '']

In [98]:
row[-1] = soup.select('tr.gift')[0].select_one('img')['src']
row

['Vegetable Basket',
 'This vegetable basket is the perfect gift for your health conscious (or overweight) friends!\nNow with super-colorful bell peppers!',
 '$15.00',
 '../img/gifts/img1.jpg']

In [100]:
gifts = []
for element in soup.select('tr.gift'):
    row = [elem.text.strip() for elem in element.select('td')]
    row[-1] = element.select_one('img')['src']
    gifts.append(row)
gifts = pd.DataFrame(gifts, columns=['item', 'description', 'cost', 'image_url'])

In [101]:
gifts

,item,description,cost,image_url
0,Vegetable Basket,This vegetable basket is the perfect gift for ...,$15.00,../img/gifts/img1.jpg
1,Russian Nesting Dolls,"Hand-painted by trained monkeys, these exquisi...","$10,000.52",../img/gifts/img2.jpg
2,Fish Painting,"If something seems fishy about this painting, ...","$10,005.00",../img/gifts/img3.jpg
3,Dead Parrot,This is an ex-parrot! Or maybe he's only resting?,$0.50,../img/gifts/img4.jpg
4,Mystery Box,"If you love suprises, this mystery box is for ...",$1.50,../img/gifts/img6.jpg

### Scraping Multiple Webpages or Websites

So far, our examples have focused on extracting data from static web pages. Now that we know how to locate and extract specific tags and attributes, we can extend this idea to collect all the URLs on a page and then scrape each newly discovered page in turn.

Programs that follow links and move from page to page in this way are called **web crawlers**, since they “crawl” across the web by traversing links between pages.

As an example, let's demonstrate how we can create our own ***Pokédex™*** by extracting multiple webpages from a pokemon website - https://pokemondb.net/

Looking at the `https://pokemondb.net/robots.txt` file, the website disallows bots only on specific pages:

```
User-agent: *
Disallow: /pokebase/search?
Disallow: /pokebase/revisions
Disallow: /pokebase/meta/search?
Disallow: /pokebase/meta/revisions
Disallow: /pokebase/rmt/search?
Disallow: /pokebase/rmt/revisions
Crawl-delay: 2
```

We also note the crawl delay value of `2` for the website.

Specifically, let's scrape and create a database for the **FireRed & LeafGreen** version of Pokemon.

In [102]:
url = 'https://pokemondb.net/pokedex/game/firered-leafgreen'
headers = {"User-Agent": "llorenzo-scraper/1.0(contact:llorenzo@aim.edu)"}

response = get_webpage(url, headers=headers, sleep_time=5)

Page has been successfully fetched! https://pokemondb.net/pokedex/game/firered-leafgreen

In [103]:
soup = BeautifulSoup(response.content, 'html5lib')

In [104]:
soup.select('div.infocard')

[<div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/bulbasaur"><img alt="Bulbasaur" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/bulbasaur.png"/></a></span><span class="infocard-lg-data text-muted"><small>#001</small><br/> <a class="ent-name" href="/pokedex/bulbasaur">Bulbasaur</a><br/> <small><a class="itype grass" href="/type/grass">Grass</a> · <a class="itype poison" href="/type/poison">Poison</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/ivysaur"><img alt="Ivysaur" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/ivysaur.png"/></a></span><span class="infocard-lg-data text-muted"><small>#002</small><br/> <a class="ent-name" href="/pokedex/ivysaur">Ivysaur</a><br/> <small><a class="itype grass" href="/type/grass">Grass</a> · <a class="itype poison" href="/type/poison">Poison</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/venusaur"><img alt="Venusaur" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/venusaur.png"/></a></span><span class="infocard-lg-data text-muted"><small>#003</small><br/> <a class="ent-name" href="/pokedex/venusaur">Venusaur</a><br/> <small><a class="itype grass" href="/type/grass">Grass</a> · <a class="itype poison" href="/type/poison">Poison</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/charmander"><img alt="Charmander" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/charmander.png"/></a></span><span class="infocard-lg-data text-muted"><small>#004</small><br/> <a class="ent-name" href="/pokedex/charmander">Charmander</a><br/> <small><a class="itype fire" href="/type/fire">Fire</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/charmeleon"><img alt="Charmeleon" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/charmeleon.png"/></a></span><span class="infocard-lg-data text-muted"><small>#005</small><br/> <a class="ent-name" href="/pokedex/charmeleon">Charmeleon</a><br/> <small><a class="itype fire" href="/type/fire">Fire</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/charizard"><img alt="Charizard" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/charizard.png"/></a></span><span class="infocard-lg-data text-muted"><small>#006</small><br/> <a class="ent-name" href="/pokedex/charizard">Charizard</a><br/> <small><a class="itype fire" href="/type/fire">Fire</a> · <a class="itype flying" href="/type/flying">Flying</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/squirtle"><img alt="Squirtle" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/squirtle.png"/></a></span><span class="infocard-lg-data text-muted"><small>#007</small><br/> <a class="ent-name" href="/pokedex/squirtle">Squirtle</a><br/> <small><a class="itype water" href="/type/water">Water</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/wartortle"><img alt="Wartortle" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/wartortle.png"/></a></span><span class="infocard-lg-data text-muted"><small>#008</small><br/> <a class="ent-name" href="/pokedex/wartortle">Wartortle</a><br/> <small><a class="itype water" href="/type/water">Water</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/blastoise"><img alt="Blastoise" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/blastoise.png"/></a></span><span class="infocard-lg-data text-muted"><small>#009</small><br/> <a class="ent-name" href="/pokedex/blastoise">Blastoise</a><br/> <small><a class="itype water" href="/type/water">Water</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/caterpie"><img alt="Caterpie" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/caterpie.png"/></a></span><span class="infocard-lg-data text-muted"><small>#010</small><br/> <a class="ent-name" href="/pokedex/caterpie">Caterpie</a><br/> <small><a class="itype bug" href="/type/bug">Bug</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/metapod"><img alt="Metapod" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/metapod.png"/></a></span><span class="infocard-lg-data text-muted"><small>#011</small><br/> <a class="ent-name" href="/pokedex/metapod">Metapod</a><br/> <small><a class="itype bug" href="/type/bug">Bug</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/butterfree"><img alt="Butterfree" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/butterfree.png"/></a></span><span class="infocard-lg-data text-muted"><small>#012</small><br/> <a class="ent-name" href="/pokedex/butterfree">Butterfree</a><br/> <small><a class="itype bug" href="/type/bug">Bug</a> · <a class="itype flying" href="/type/flying">Flying</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/weedle"><img alt="Weedle" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/weedle.png"/></a></span><span class="infocard-lg-data text-muted"><small>#013</small><br/> <a class="ent-name" href="/pokedex/weedle">Weedle</a><br/> <small><a class="itype bug" href="/type/bug">Bug</a> · <a class="itype poison" href="/type/poison">Poison</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/kakuna"><img alt="Kakuna" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/kakuna.png"/></a></span><span class="infocard-lg-data text-muted"><small>#014</small><br/> <a class="ent-name" href="/pokedex/kakuna">Kakuna</a><br/> <small><a class="itype bug" href="/type/bug">Bug</a> · <a class="itype poison" href="/type/poison">Poison</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/beedrill"><img alt="Beedrill" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/beedrill.png"/></a></span><span class="infocard-lg-data text-muted"><small>#015</small><br/> <a class="ent-name" href="/pokedex/beedrill">Beedrill</a><br/> <small><a class="itype bug" href="/type/bug">Bug</a> · <a class="itype poison" href="/type/poison">Poison</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/pidgey"><img alt="Pidgey" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/pidgey.png"/></a></span><span class="infocard-lg-data text-muted"><small>#016</small><br/> <a class="ent-name" href="/pokedex/pidgey">Pidgey</a><br/> <small><a class="itype normal" href="/type/normal">Normal</a> · <a class="itype flying" href="/type/flying">Flying</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/pidgeotto"><img alt="Pidgeotto" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/pidgeotto.png"/></a></span><span class="infocard-lg-data text-muted"><small>#017</small><br/> <a class="ent-name" href="/pokedex/pidgeotto">Pidgeotto</a><br/> <small><a class="itype normal" href="/type/normal">Normal</a> · <a class="itype flying" href="/type/flying">Flying</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/pidgeot"><img alt="Pidgeot" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/pidgeot.png"/></a></span><span class="infocard-lg-data text-muted"><small>#018</small><br/> <a class="ent-name" href="/pokedex/pidgeot">Pidgeot</a><br/> <small><a class="itype normal" href="/type/normal">Normal</a> · <a class="itype flying" href="/type/flying">Flying</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/rattata"><img alt="Rattata" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/rattata.png"/></a></span><span class="infocard-lg-data text-muted"><small>#019</small><br/> <a class="ent-name" href="/pokedex/rattata">Rattata</a><br/> <small><a class="itype normal" href="/type/normal">Normal</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/raticate"><img alt="Raticate" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/raticate.png"/></a></span><span class="infocard-lg-data text-muted"><small>#020</small><br/> <a class="ent-name" href="/pokedex/raticate">Raticate</a><br/> <small><a class="itype normal" href="/type/normal">Normal</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/spearow"><img alt="Spearow" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/spearow.png"/></a></span><span class="infocard-lg-data text-muted"><small>#021</small><br/> <a class="ent-name" href="/pokedex/spearow">Spearow</a><br/> <small><a class="itype normal" href="/type/normal">Normal</a> · <a class="itype flying" href="/type/flying">Flying</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/fearow"><img alt="Fearow" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/fearow.png"/></a></span><span class="infocard-lg-data text-muted"><small>#022</small><br/> <a class="ent-name" href="/pokedex/fearow">Fearow</a><br/> <small><a class="itype normal" href="/type/normal">Normal</a> · <a class="itype flying" href="/type/flying">Flying</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/ekans"><img alt="Ekans" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/ekans.png"/></a></span><span class="infocard-lg-data text-muted"><small>#023</small><br/> <a class="ent-name" href="/pokedex/ekans">Ekans</a><br/> <small><a class="itype poison" href="/type/poison">Poison</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/arbok"><img alt="Arbok" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/arbok.png"/></a></span><span class="infocard-lg-data text-muted"><small>#024</small><br/> <a class="ent-name" href="/pokedex/arbok">Arbok</a><br/> <small><a class="itype poison" href="/type/poison">Poison</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/pikachu"><img alt="Pikachu" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/pikachu.png"/></a></span><span class="infocard-lg-data text-muted"><small>#025</small><br/> <a class="ent-name" href="/pokedex/pikachu">Pikachu</a><br/> <small><a class="itype electric" href="/type/electric">Electric</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/raichu"><img alt="Raichu" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/raichu.png"/></a></span><span class="infocard-lg-data text-muted"><small>#026</small><br/> <a class="ent-name" href="/pokedex/raichu">Raichu</a><br/> <small><a class="itype electric" href="/type/electric">Electric</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/sandshrew"><img alt="Sandshrew" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/sandshrew.png"/></a></span><span class="infocard-lg-data text-muted"><small>#027</small><br/> <a class="ent-name" href="/pokedex/sandshrew">Sandshrew</a><br/> <small><a class="itype ground" href="/type/ground">Ground</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/sandslash"><img alt="Sandslash" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/sandslash.png"/></a></span><span class="infocard-lg-data text-muted"><small>#028</small><br/> <a class="ent-name" href="/pokedex/sandslash">Sandslash</a><br/> <small><a class="itype ground" href="/type/ground">Ground</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/nidoran-f"><img alt="Nidoran♀" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/nidoran-f.png"/></a></span><span class="infocard-lg-data text-muted"><small>#029</small><br/> <a class="ent-name" href="/pokedex/nidoran-f">Nidoran♀</a><br/> <small><a class="itype poison" href="/type/poison">Poison</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/nidorina"><img alt="Nidorina" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/nidorina.png"/></a></span><span class="infocard-lg-data text-muted"><small>#030</small><br/> <a class="ent-name" href="/pokedex/nidorina">Nidorina</a><br/> <small><a class="itype poison" href="/type/poison">Poison</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/nidoqueen"><img alt="Nidoqueen" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/nidoqueen.png"/></a></span><span class="infocard-lg-data text-muted"><small>#031</small><br/> <a class="ent-name" href="/pokedex/nidoqueen">Nidoqueen</a><br/> <small><a class="itype poison" href="/type/poison">Poison</a> · <a class="itype ground" href="/type/ground">Ground</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/nidoran-m"><img alt="Nidoran♂" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/nidoran-m.png"/></a></span><span class="infocard-lg-data text-muted"><small>#032</small><br/> <a class="ent-name" href="/pokedex/nidoran-m">Nidoran♂</a><br/> <small><a class="itype poison" href="/type/poison">Poison</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/nidorino"><img alt="Nidorino" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/nidorino.png"/></a></span><span class="infocard-lg-data text-muted"><small>#033</small><br/> <a class="ent-name" href="/pokedex/nidorino">Nidorino</a><br/> <small><a class="itype poison" href="/type/poison">Poison</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/nidoking"><img alt="Nidoking" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/nidoking.png"/></a></span><span class="infocard-lg-data text-muted"><small>#034</small><br/> <a class="ent-name" href="/pokedex/nidoking">Nidoking</a><br/> <small><a class="itype poison" href="/type/poison">Poison</a> · <a class="itype ground" href="/type/ground">Ground</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/clefairy"><img alt="Clefairy" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/clefairy.png"/></a></span><span class="infocard-lg-data text-muted"><small>#035</small><br/> <a class="ent-name" href="/pokedex/clefairy">Clefairy</a><br/> <small><a class="itype normal" href="/type/normal">Normal</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/clefable"><img alt="Clefable" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/clefable.png"/></a></span><span class="infocard-lg-data text-muted"><small>#036</small><br/> <a class="ent-name" href="/pokedex/clefable">Clefable</a><br/> <small><a class="itype normal" href="/type/normal">Normal</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/vulpix"><img alt="Vulpix" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/vulpix.png"/></a></span><span class="infocard-lg-data text-muted"><small>#037</small><br/> <a class="ent-name" href="/pokedex/vulpix">Vulpix</a><br/> <small><a class="itype fire" href="/type/fire">Fire</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/ninetales"><img alt="Ninetales" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/ninetales.png"/></a></span><span class="infocard-lg-data text-muted"><small>#038</small><br/> <a class="ent-name" href="/pokedex/ninetales">Ninetales</a><br/> <small><a class="itype fire" href="/type/fire">Fire</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/jigglypuff"><img alt="Jigglypuff" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/jigglypuff.png"/></a></span><span class="infocard-lg-data text-muted"><small>#039</small><br/> <a class="ent-name" href="/pokedex/jigglypuff">Jigglypuff</a><br/> <small><a class="itype normal" href="/type/normal">Normal</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/wigglytuff"><img alt="Wigglytuff" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/wigglytuff.png"/></a></span><span class="infocard-lg-data text-muted"><small>#040</small><br/> <a class="ent-name" href="/pokedex/wigglytuff">Wigglytuff</a><br/> <small><a class="itype normal" href="/type/normal">Normal</a></small></span></div>,
 <div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/zubat"><img alt="Zubat" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/zubat.png"/></a></span><span class="infocard-lg-data text-muted"><small>#041</small><br/> <a class="ent-name" href="/pokedex/zubat">Zubat</a><br/> <small><a class="itype poison" href="/type/poison">Poison</a> · <a class="itype flying" href="/type/flying">Flying</a></small></span></div>,

In [105]:
soup.select('div.infocard')[0]

<div class="infocard"><span class="infocard-lg-img"><a href="/pokedex/bulbasaur"><img alt="Bulbasaur" class="img-fixed img-sprite img-sprite-v6" loading="lazy" src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/bulbasaur.png"/></a></span><span class="infocard-lg-data text-muted"><small>#001</small><br/> <a class="ent-name" href="/pokedex/bulbasaur">Bulbasaur</a><br/> <small><a class="itype grass" href="/type/grass">Grass</a> · <a class="itype poison" href="/type/poison">Poison</a></small></span></div>

In [109]:
soup.select('div.infocard')[0].select_one('a.ent-name').text

'Bulbasaur'

In [111]:
soup.select('div.infocard')[0].small.text

'#001'

In [115]:
','.join([itype.text for itype in soup.select('div.infocard')[0].select('a.itype')])

'Grass,Poison'

In [117]:
soup.select('div.infocard')[0].img['src']

'https://img.pokemondb.net/sprites/ruby-sapphire/normal/bulbasaur.png'

In [122]:
f'https://pokemondb.net{soup.select('div.infocard')[0].a['href']}'

'https://pokemondb.net/pokedex/bulbasaur'

In [126]:
pokemons = []
for elem in soup.select('div.infocard'):
    pokemons.append({
        'pokemon_id': elem.small.text,
        'name': elem.select_one('a.ent-name').text,
        'type': ','.join([itype.text for itype in elem.select('a.itype')]),
        'image_url': elem.img['src'],
        'pokedex_url': f'https://pokemondb.net{elem.a['href']}'
    })

In [127]:
pd.DataFrame(pokemons)

,pokemon_id,name,type,image_url,pokedex_url
0,#001,Bulbasaur,"Grass,Poison",https://img.pokemondb.net/sprites/ruby-sapphir...,https://pokemondb.net/pokedex/bulbasaur
1,#002,Ivysaur,"Grass,Poison",https://img.pokemondb.net/sprites/ruby-sapphir...,https://pokemondb.net/pokedex/ivysaur
2,#003,Venusaur,"Grass,Poison",https://img.pokemondb.net/sprites/ruby-sapphir...,https://pokemondb.net/pokedex/venusaur
3,#004,Charmander,Fire,https://img.pokemondb.net/sprites/ruby-sapphir...,https://pokemondb.net/pokedex/charmander
4,#005,Charmeleon,Fire,https://img.pokemondb.net/sprites/ruby-sapphir...,https://pokemondb.net/pokedex/charmeleon
...,...,...,...,...,...
146,#147,Dratini,Dragon,https://img.pokemondb.net/sprites/ruby-sapphir...,https://pokemondb.net/pokedex/dratini
147,#148,Dragonair,Dragon,https://img.pokemondb.net/sprites/ruby-sapphir...,https://pokemondb.net/pokedex/dragonair
148,#149,Dragonite,"Dragon,Flying",https://img.pokemondb.net/sprites/ruby-sapphir...,https://pokemondb.net/pokedex/dragonite
149,#150,Mewtwo,Psychic,https://img.pokemondb.net/sprites/ruby-sapphir...,https://pokemondb.net/pokedex/mewtwo
150,#151,Mew,Psychic,https://img.pokemondb.net/sprites/ruby-sapphir...,https://pokemondb.net/pokedex/mew

Let's populate our pokedex database further by scraping the height, weight, and base stats of the pokemon in our database.

In [ ]:
# This code runs for about 15 minutes
for i, pokemon in pokemons.iterrows():
    # Scrape pokedex webpage of current pokemon
    response = get_webpage(pokemon['pokedex_url'], headers, sleep_time=5)
    soup = BeautifulSoup(response.content, 'html5lib')

    # Get height and weight
    pokemon['height'] = soup.find('th', string='Height').next_sibling.next_sibling.text
    pokemon['weight'] = soup.find('th', string='Weight').next_sibling.next_sibling.text

    # Parse the stats
    stats = {}
    for stat_elem in (soup.find('h2', string='Base stats').next_sibling
                          .next_sibling.select_one('table.vitals-table')
                          .find_all('th', limit=6)):
        stats[stat_elem.text] = int(stat_elem.next_sibling.next_sibling.text)
    pokemon['stats'] = stats

    # Write to output file
    with open('outputs/pokedex.jsonl', 'a') as f:
        f.write(pokemon.to_json() + '\n')

<img src="images/banner-down.png" style="width: 100%;">